# Copyright (c) 2014, UChicago Argonne, LLC
SOURCES +=  src/mvc/DeselectableTreeView.cpp \
    src/solver/asa047.cpp \
    src/solver/AbstractSolver.cpp \
    src/solver/Solver.cpp \
    src/solver/CoordinateTransformer.cpp \
    src/solver/PythonTransformer.cpp \
    src/solver/NelderMeadSolver.cpp \
    src/solver/PythonSolver.cpp \
    src/mvc/SolverWidget.cpp \
    src/mvc/AbstractWindowModel.cpp \
    src/mvc/AbstractWindowController.cpp \
    src/mvc/TIFFModel.cpp \
    src/mvc/TIFFWidget.cpp \
    src/mvc/TIFFController.cpp \
    src/mvc/SWSWidget.cpp \
    src/mvc/SWSModel.cpp \
    src/mvc/SpectraWidget.cpp \
    src/mvc/XrfAnalyzedCounts.cpp \
    src/mvc/MapsH5Model.cpp \
    src/mvc/MapsElementsWidget.cpp \
    src/mvc/MapsWorkspaceModel.cpp \
    src/mvc/MapsWorkspaceWidget.cpp \
    src/preferences/Preferences.cpp \
    src/preferences/Attribute.cpp \
    src/preferences/AttributeGroup.cpp \
    src/preferences/AttributeGroupModel.cpp \
    src/preferences/PreferencesPythonFunc.cpp \
    src/preferences/PreferencesDisplay.cpp \
    src/preferences/PreferencesMicroPv.cpp \
    src/preferences/PreferencesDialog.cpp \
    src/preferences/CoordinateTransformGlobals.cpp \
    src/preferences/SolverTable.cpp \
    src/preferences/SolverParameterWidget.cpp \
    src/preferences/PreferencesSolverOption.cpp \
    src/preferences/SolverParameterParse.cpp \
    src/preferences/ProfileTable.cpp \
    src/preferences/AttributeTableModel.cpp \
    src/preferences/PythonSolverProfileWidget.cpp \
    src/preferences/Profile.cpp \
    src/preferences/PreferencesAutoSave.cpp \
    src/preferences/PreferencesExport.cpp \
    src/core/PythonLoader.cpp \
    src/core/RegionCaller.cpp \
    src/core/ShellRegionCaller.cpp \
    src/core/PythonRegionCaller.cpp \
    src/core/SubWindow.cpp \
    src/core/uProbeX.cpp \
    src/main.cpp
HEADERS = src/mvc/DeselectableTreeView.h \
    src/solver/asa047.hpp \
    src/solver/AbstractSolver.h \
    src/solver/Solver.h \
    src/solver/CoordinateTransformer.h \
    src/solver/PythonTransformer.h \
    src/solver/NelderMeadSolver.h \
    src/solver/PythonSolver.h \
    src/mvc/SolverWidget.h \
    src/mvc/AbstractWindowModel.h \
    src/mvc/AbstractWindowController.h \
    src/mvc/SWSModel.h \
    src/mvc/TIFFModel.h \
    src/mvc/TIFFWidget.h \
    src/mvc/TIFFController.h \
    src/mvc/SWSWidget.h \
    src/mvc/SpectraWidget.h \
    src/mvc/XrfAnalyzedCounts.h \
    src/mvc/MapsH5Model.h \
    src/mvc/MapsElementsWidget.h \
    src/mvc/MapsWorkspaceModel.h \
    src/mvc/MapsWorkspaceWidget.h \
    src/preferences/Preferences.h \
    src/preferences/PreferencesDisplay.h \
    src/preferences/PreferencesMicroPv.h \
    src/preferences/PreferencesDialog.h \
    src/preferences/Attribute.h \
    src/preferences/AttributeGroup.h \
    src/preferences/AttributeGroupModel.h \
    src/preferences/PreferencesPythonFunc.h \
    src/preferences/SolverTable.h \
    src/preferences/SolverParameterWidget.h \
    src/preferences/PreferencesSolverOption.h \
    src/preferences/CoordinateTransformGlobals.h \
    src/preferences/SolverParameterParse.h \
    src/preferences/ProfileTable.h \
    src/preferences/AttributeTableModel.h \
    src/preferences/PythonSolverProfileWidget.h \
    src/preferences/Profile.h \
    src/preferences/PreferencesAutoSave.h \
    src/preferences/PreferencesExport.h \
    src/core/PythonLoader.h \
    src/core/RegionCaller.h \
    src/core/ShellRegionCaller.h \
    src/core/PythonRegionCaller.h \
    src/core/SubWindow.h \
    src/core/uProbeX.h


