# Copyright (c) 2014, UChicago Argonne, LLC
SOURCES +=  src/mvc/DeselectableTreeView.cpp \
    src/solver/asa047.cpp \
    src/solver/AbstractSolver.cpp \
    src/solver/Solver.cpp \
    src/solver/CoordinateTransformer.cpp \
    src/solver/PythonTransformer.cpp \
    src/solver/NelderMeadSolver.cpp \
    src/solver/PythonSolver.cpp \
    src/mvc/SolverWidget.cpp \
    src/core/PythonLoader.cpp \
    src/core/RegionCaller.cpp \
    src/core/ShellRegionCaller.cpp \
    src/core/PythonRegionCaller.cpp \
    src/core/AbstractWindowModel.cpp \
    src/core/AbstractWindowController.cpp \
    src/core/SubWindow.cpp \
    src/core/SWSModel.cpp \
    src/core/TIFFModel.cpp \
    src/core/TIFFWidget.cpp \
    src/core/TIFFController.cpp \
    src/core/SWSWidget.cpp \
    src/preferences/Preferences.cpp \
    src/preferences/Attribute.cpp \
    src/preferences/AttributeGroup.cpp \
    src/preferences/AttributeGroupModel.cpp \
    src/preferences/PreferencesPythonFunc.cpp \
    src/preferences/PreferencesDisplay.cpp \
    src/preferences/PreferencesMicroPv.cpp \
    src/preferences/PreferencesDialog.cpp \
    src/preferences/CoordinateTransformGlobals.cpp \
    src/preferences/SolverTable.cpp \
    src/preferences/SolverParameterWidget.cpp \
    src/preferences/PreferencesSolverOption.cpp \
    src/preferences/SolverParameterParse.cpp \
    src/core/uProbeX.cpp \
    src/main.cpp \ 
    src/preferences/ProfileTable.cpp \
    src/preferences/AttributeTableModel.cpp \
    src/preferences/PythonSolverProfileWidget.cpp \
    src/preferences/Profile.cpp \
    src/preferences/PreferencesAutoSave.cpp \
    src/preferences/PreferencesExport.cpp
HEADERS = include/mvc/DeselectableTreeView.h \
    include/solver/asa047.hpp \
    include/solver/AbstractSolver.h \
    include/solver/Solver.h \
    include/solver/CoordinateTransformer.h \
    include/solver/PythonTransformer.h \
    include/solver/NelderMeadSolver.h \
    include/solver/PythonSolver.h \
    include/mvc/SolverWidget.h \
    include/core/PythonLoader.h \
    include/core/RegionCaller.h \
    include/core/ShellRegionCaller.h \
    include/core/PythonRegionCaller.h \
    include/core/AbstractWindowModel.h \
    include/core/AbstractWindowController.h \
    include/core/SubWindow.h \
    include/core/SWSModel.h \
    include/core/TIFFModel.h \
    include/core/TIFFWidget.h \
    include/core/TIFFController.h \
    include/core/SWSWidget.h \
    include/preferences/Preferences.h \
    include/preferences/PreferencesDisplay.h \
    include/preferences/PreferencesMicroPv.h \
    include/preferences/PreferencesDialog.h \
    include/preferences/Attribute.h \
    include/preferences/AttributeGroup.h \
    include/preferences/AttributeGroupModel.h \
    include/preferences/PreferencesPythonFunc.h \
    include/preferences/SolverTable.h \
    include/preferences/SolverParameterWidget.h \
    include/preferences/PreferencesSolverOption.h \
    include/preferences/CoordinateTransformGlobals.h \
    include/preferences/SolverParameterParse.h \
    include/core/uProbeX.h \ 
    include/preferences/ProfileTable.h \
    include/preferences/AttributeTableModel.h \
    include/preferences/PythonSolverProfileWidget.h \
    include/preferences/Profile.h \
    include/preferences/PreferencesAutoSave.h \
    include/preferences/PreferencesExport.h

